modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"

[[mods]]
modId="hearttogether"
version="1.0.0"
displayName="HeartTogether"
logoFile="hearttogether.png"
credits="DY_XiaoJiaZi"
authors="DY_XiaoJiaZi"
description='''
A mod that allows players to share health points, absorption and healing effects.
'''
[[dependencies.hearttogether]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"
[[dependencies.hearttogether]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"